version: "3.3"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5431:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - PMA_HOST=mysql
    ports:
      - 8080:80
